FROM python:3.13-alpine

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir fastapi gunicorn uvicorn

COPY gunicorn_config.py .

COPY src src

RUN chown -R appuser:appgroup /app

USER appuser

CMD ["gunicorn", "-c", "gunicorn_config.py"]