FROM ghcr.io/astral-sh/uv:python3.13-alpine

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY pyproject.toml .

RUN uv sync --no-dev

COPY gunicorn_config.py .

COPY src src

RUN chown -R appuser:appgroup /app

USER appuser

CMD ["uv","run","gunicorn", "-c", "gunicorn_config.py"]